name: Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
